import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { StarknetProvider } from "./components/starknet-provider";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StarknetProvider>
        <body className="relative w-full bg-[#08001F] bg-cover bg-center bg-no-repeat">
          <Navbar />
          {children}
          <Footer />
        </body>

      </StarknetProvider>
    </html>
  );
}
