import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Providers } from "./components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="relative w-full bg-main-bg bg-cover bg-center bg-no-repeat pt-[120px]">
          <Navbar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
